### ISSUE TITLE
Definition formula of  mc_df['mc_delta']

### ISSUE THREAD

**Issue by hiroki-kurasawa** [sibylhe/mmm_stan#4]
Hi Sibyl

thanks to this repository, I now have a deeper understanding of marketing mix modeling
 
 I have a question about line 541 of mmm_stan.py.
 https://github.com/sibylhe/mmm_stan/blob/main/mmm_stan.py#L541
 
 in  [README](https://github.com/sibylhe/mmm_stan#decompose-sales-to-media-channels-contribution), definition of delta is `mc_pred - mc_ture`, but delta is `mc_true - mc_pred` in line 483 . Is there any problem?

**Comment by sibylhe** [comment]
Indeed! Fixed it. Thanks for pointing out this error!

**Comment by hiroki-kurasawa** [comment]
you should fix it as `mc_df['mc_delta'] =  mc_df['mc_pred'] - mc_df['mc_true']` instead of `mc_df['mc_delta'] =  ['mc_pred'] - mc_df['mc_true']`

https://github.com/sibylhe/mmm_stan/blob/main/mmm_stan.py#L541

**Comment by sibylhe** [comment]
👌
