### ISSUE TITLE
Different results between Jupyter Notebook and Readme

### ISSUE THREAD

**Issue by Steven-Livingstone** [sibylhe/mmm_stan#50]
First of all AWESOME STUFF!

However, in an effort to reproduce your results locally I spotted a few differences between your Jupyter notebook results and the ones given in the readme.

| Value                       | stan_mmm.ipynb      | readme.md |
|-----------------------------|---------------------|-----------|
| MAPE                        | 26.06330645337451   | 8.63      |
| RMSE (log-log model)        | 0.13647800963534104 | 0.04977   |
| MAPE (multiplicative model) | 20.313393234793644  | 15.71     |

Have the Readme results been generated using different priors/parameters, or am I missing something obvious?

**Comment by sibylhe** [comment]
Don't bother, it doesn't really matter. They were generated from different datasets. The dataset published is tweaked, and the Jupyter notebook is done on top of it.

**Comment by Steven-Livingstone** [comment]
Ah, that makes sense then. 

Thanks for the quick clarification. :)
